INSERT IGNORE INTO badges (slug, name, description, icon, category) VALUES
('first_session',     'First Word',        'Completed your first practice session',                        '🎤', 'practice'),
('scenario_explorer', 'Explorer',          'Tried 5 different scenarios',                                  '🗺️', 'practice'),
('comeback',          'Comeback',          'Retried a scenario after a low score and scored above 70',      '💪', 'practice'),
('fifty_sessions',    'Persistent',        'Completed 50 total sessions',                                  '🏃', 'practice'),
('century',           'Century',           'Completed 100 total sessions',                                 '💯', 'practice'),
('filler_free',       'Filler Free',       'Scored zero filler words in a session',                        '🤐', 'skill'),
('speed_control',     'Speed Control',     'Hit ideal WPM range 3 sessions in a row',                      '🎯', 'skill'),
('structured_mind',   'Structured Mind',   'Scored 5/5 on Structure in any session',                       '🏗️', 'skill'),
('vocab_master',      'Vocabulary Master', 'Scored 5/5 on Vocabulary in any session',                      '📚', 'skill'),
('week_warrior',      'Week Warrior',      '7-day practice streak',                                        '🔥', 'streak'),
('fortnight',         'Fortnight',         '14-day practice streak',                                       '⚡', 'streak'),
('iron_habit',        'Iron Habit',        '30-day practice streak',                                       '🦾', 'streak'),
('unstoppable',       'Unstoppable',       '60-day practice streak',                                       '🚀', 'streak'),
('top_10',            'Top 10',            'Finished in top 10 in a monthly leaderboard',                  '🥇', 'leaderboard'),
('month_champion',    'Month Champion',    'Finished #1 in a monthly leaderboard',                         '👑', 'leaderboard');

INSERT IGNORE INTO scenarios (id, category, title, context, question, register, vocab_level, comm_goal, common_mistakes, ideal_wpm_min, ideal_wpm_max, sort_order) VALUES

('sc-001', 'professional_daily',
  'Daily Standup Update',
  'Your team has a quick 15-minute standup every morning. Your manager asks for your update. You are a software developer and yesterday you were working on a bug fix.',
  'What did you work on yesterday, what are you doing today, and do you have any blockers?',
  'semi_formal', 'professional', 'clarity',
  '["Too long", "No clear structure", "Vague language like I was doing some work", "Saying um basically at start"]',
  100, 130, 1),

('sc-002', 'professional_daily',
  'Asking for a Deadline Extension',
  'You are working on a feature that was supposed to be delivered by Friday. It is Wednesday and you realise you need 2 more days. Your manager is about to message you for an update.',
  'Your manager asks: "Will the feature be ready by Friday as planned?" How do you respond?',
  'semi_formal', 'professional', 'confidence',
  '["Apologising too much", "Being vague about the reason", "Not giving a new deadline", "Sounding unsure"]',
  100, 130, 2),

('sc-003', 'professional_daily',
  'Introducing Yourself to a New Team',
  'You have just joined a new company as a Senior Engineer. Today is your first team meeting where everyone is introducing themselves.',
  'The team lead says: "Please introduce yourself to the team." Go ahead.',
  'semi_formal', 'professional', 'confidence',
  '["Too short or too long", "Listing only job history without personality", "Saying I am from XYZ place only", "No mention of what you bring to the team"]',
  110, 140, 3),

('sc-004', 'client_call',
  'Opening a Call with a US Client',
  'You are a project manager at an IT services company. You have a weekly sync with your US-based client. It is Monday morning their time, Friday evening your time.',
  'The client answers the call. How do you open the conversation and set the agenda for today\'s sync?',
  'formal', 'professional', 'clarity',
  '["Jumping straight to business without any small talk", "Over-explaining", "Saying so basically let us start", "Not confirming the agenda"]',
  100, 125, 4),

('sc-005', 'client_call',
  'Handling "I Did Not Understand You"',
  'You are on a video call with a UK-based client. You just explained a technical decision your team made. The client says: "Sorry, I did not quite follow that."',
  'The client says: "Could you explain that again? I am not sure I understood." How do you respond?',
  'formal', 'professional', 'clarity',
  '["Repeating the exact same words faster", "Saying sorry sorry many times", "Becoming defensive", "Not using a simpler analogy or example"]',
  95, 120, 5),

('sc-006', 'client_call',
  'Pushing Back on an Unreasonable Demand',
  'Your client wants a feature added to the product by next week. Your team has estimated it will take three weeks minimum. You need to push back without damaging the relationship.',
  'The client says: "I really need this feature live by next Friday. Can your team make it happen?" How do you respond?',
  'formal', 'professional', 'confidence',
  '["Saying yes and then failing to deliver", "Being too blunt and saying that is impossible", "Not offering an alternative timeline", "Panicking and hedging too much"]',
  100, 125, 6),

('sc-007', 'interview',
  'Tell Me About Yourself',
  'You are in a job interview for a Senior Product Manager role at a Bangalore-based startup. The interviewer has just started the interview.',
  'The interviewer says: "So tell me a little about yourself and your background." Go ahead.',
  'formal', 'professional', 'structure',
  '["Starting from childhood", "Just reading out the CV", "Taking more than 3 minutes", "No clear narrative arc", "Ending abruptly"]',
  110, 135, 7),

('sc-008', 'interview',
  'Why Do You Want to Leave Your Current Job?',
  'You are in an interview. You have been at your current company for 3 years and are looking for a change. The reason is partly that growth has stalled and partly that the culture is not great.',
  'The interviewer asks: "Why are you looking to move on from your current role?"',
  'formal', 'professional', 'confidence',
  '["Badmouthing the current company", "Being too honest about toxic culture in a negative way", "Saying only for money", "Vague answers like looking for better opportunities"]',
  100, 125, 8),

('sc-009', 'social',
  'Small Talk at an Office Party',
  'Your company is having its annual party. You are standing near the snack table and someone from another team you have seen in the office but never spoken to walks up next to you.',
  'They smile at you. How do you start a conversation?',
  'casual', 'conversational', 'confidence',
  '["Silence or just smiling back", "Immediately asking their designation", "Too formal language", "Very short one-word answers that kill the conversation"]',
  120, 150, 9),

('sc-010', 'interview',
  'Explaining a Project Delay to Your Manager',
  'You are in a one-on-one with your manager. A project you were leading is two weeks behind schedule due to unexpected technical challenges and one team member being sick.',
  'Your manager asks: "The project was supposed to go live last week. What happened and where do we stand?"',
  'semi_formal', 'professional', 'structure',
  '["Being defensive", "Blaming the team member who was sick", "No clear plan for recovery", "Vague timeline for when it will be done"]',
  100, 130, 10);

UPDATE scenarios SET is_daily = 1, daily_date = CURDATE() WHERE id = 'sc-004';
